# Generated by Django 4.0.3 on 2022-03-28 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(choices=[('Acts of Service', 'Acts Of Service'), ('Receiving Gifts', 'Receiving Gifts'), ('Quality Time', 'Quality Time'), ('Words of Affirmation', 'Words Of Affirmation'), ('Physical Touch', 'Physical Touch')], max_length=20)),
                ('two', models.CharField(choices=[('Acts of Service', 'Acts Of Service'), ('Receiving Gifts', 'Receiving Gifts'), ('Quality Time', 'Quality Time'), ('Words of Affirmation', 'Words Of Affirmation'), ('Physical Touch', 'Physical Touch')], max_length=20)),
                ('three', models.CharField(choices=[('Acts of Service', 'Acts Of Service'), ('Receiving Gifts', 'Receiving Gifts'), ('Quality Time', 'Quality Time'), ('Words of Affirmation', 'Words Of Affirmation'), ('Physical Touch', 'Physical Touch')], max_length=20)),
                ('four', models.CharField(choices=[('Acts of Service', 'Acts Of Service'), ('Receiving Gifts', 'Receiving Gifts'), ('Quality Time', 'Quality Time'), ('Words of Affirmation', 'Words Of Affirmation'), ('Physical Touch', 'Physical Touch')], max_length=20)),
                ('five', models.CharField(choices=[('Acts of Service', 'Acts Of Service'), ('Receiving Gifts', 'Receiving Gifts'), ('Quality Time', 'Quality Time'), ('Words of Affirmation', 'Words Of Affirmation'), ('Physical Touch', 'Physical Touch')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
