# Generated by Django 4.0.3 on 2022-04-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_love'),
    ]

    operations = [
        migrations.RenameField(
            model_name='love',
            old_name='user',
            new_name='owner',
        ),
    ]
