# Generated by Django 4.0.3 on 2022-04-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_love_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='love',
            old_name='owner',
            new_name='user',
        ),
    ]
